// automatically generated by the FlatBuffers compiler, do not modify

package metrics

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AbsentHistogramValue struct {
	_tab flatbuffers.Table
}

func GetRootAsAbsentHistogramValue(buf []byte, offset flatbuffers.UOffsetT) *AbsentHistogramValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AbsentHistogramValue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AbsentHistogramValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AbsentHistogramValue) Table() flatbuffers.Table {
	return rcv._tab
}

func AbsentHistogramValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AbsentHistogramValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
