// automatically generated by the FlatBuffers compiler, do not modify

package metrics

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IntValue struct {
	_tab flatbuffers.Table
}

func GetRootAsIntValue(buf []byte, offset flatbuffers.UOffsetT) *IntValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IntValue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *IntValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IntValue) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IntValue) Value() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IntValue) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func IntValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func IntValueAddValue(builder *flatbuffers.Builder, value int32) {
	builder.PrependInt32Slot(0, value, 0)
}
func IntValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
