// automatically generated by the FlatBuffers compiler, do not modify

package metrics

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UintValue struct {
	_tab flatbuffers.Table
}

func GetRootAsUintValue(buf []byte, offset flatbuffers.UOffsetT) *UintValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UintValue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *UintValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UintValue) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UintValue) Value() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UintValue) MutateValue(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func UintValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UintValueAddValue(builder *flatbuffers.Builder, value uint32) {
	builder.PrependUint32Slot(0, value, 0)
}
func UintValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
