// automatically generated by the FlatBuffers compiler, do not modify

package circonus

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AbsentStringValue struct {
	_tab flatbuffers.Table
}

func GetRootAsAbsentStringValue(buf []byte, offset flatbuffers.UOffsetT) *AbsentStringValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AbsentStringValue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AbsentStringValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AbsentStringValue) Table() flatbuffers.Table {
	return rcv._tab
}

func AbsentStringValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AbsentStringValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
