// automatically generated by the FlatBuffers compiler, do not modify

package circonus

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AbsentNumericValue struct {
	_tab flatbuffers.Table
}

func GetRootAsAbsentNumericValue(buf []byte, offset flatbuffers.UOffsetT) *AbsentNumericValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AbsentNumericValue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AbsentNumericValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AbsentNumericValue) Table() flatbuffers.Table {
	return rcv._tab
}

func AbsentNumericValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AbsentNumericValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
