// automatically generated by the FlatBuffers compiler, do not modify

package circonus

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetricList struct {
	_tab flatbuffers.Table
}

func GetRootAsMetricList(buf []byte, offset flatbuffers.UOffsetT) *MetricList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetricList{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *MetricList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetricList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetricList) Metrics(obj *Metric, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MetricList) MetricsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MetricListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetricListAddMetrics(builder *flatbuffers.Builder, metrics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(metrics), 0)
}
func MetricListStartMetricsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MetricListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
