// automatically generated by the FlatBuffers compiler, do not modify

package circonus

const (
	MetricValueUnionNONE = 0
	MetricValueUnionIntValue = 1
	MetricValueUnionUintValue = 2
	MetricValueUnionLongValue = 3
	MetricValueUnionUlongValue = 4
	MetricValueUnionDoubleValue = 5
	MetricValueUnionStringValue = 6
	MetricValueUnionHistogram = 7
	MetricValueUnionAbsentNumericValue = 8
	MetricValueUnionAbsentStringValue = 9
	MetricValueUnionAbsentHistogramValue = 10
)

var EnumNamesMetricValueUnion = map[int]string{
	MetricValueUnionNONE:"NONE",
	MetricValueUnionIntValue:"IntValue",
	MetricValueUnionUintValue:"UintValue",
	MetricValueUnionLongValue:"LongValue",
	MetricValueUnionUlongValue:"UlongValue",
	MetricValueUnionDoubleValue:"DoubleValue",
	MetricValueUnionStringValue:"StringValue",
	MetricValueUnionHistogram:"Histogram",
	MetricValueUnionAbsentNumericValue:"AbsentNumericValue",
	MetricValueUnionAbsentStringValue:"AbsentStringValue",
	MetricValueUnionAbsentHistogramValue:"AbsentHistogramValue",
}

